service: delivery

plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize
 - serverless-offline
 - serverless-dynamodb-local

provider:
 name: aws
 runtime: nodejs12.x
 environment:
    DELIVERY_TABLE_NAME: ${self:custom.deliveryTable.name}
    DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodbURL}
 iamRoleStatements: ${file(iam/deliveryTableIAM.yml)}
    
resources:
    Resources:
        deliveryTable: ${file(resources/deliveryTable.yml):deliveryTable}
        
custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true
  endpoints:
    dynamodbURL: 'http://localhost:8000'
  deliveryTable:
    name: ${self:provider.stage}-delivery
    arn: !GetAtt deliveryTable.Arn

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}
