name: Sentry integration

on: ['push']
jobs:
  integrate-with-sentry:
    name: Config Sentry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sentry configuration
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production